## Datasets

### 1.  Avocado price dataset

- Dataset link : https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/avocado.csv

#### Problem Statement
- Avacard-corp avocados are sourced from over 1000 growers owning over 65,000 acres across California, Mexico, Chile, and Peru. 

- With generations of experience growing, packing, and shipping avocados, they have a deep understanding of the avocado industry. 

- Their aim is to source quality fruit that’s sustainably grown and handled in the most efficient, shortest supply route possible.

- They want to increase their supply throughout the United States and need to make sure that they are selling their products at the best possible price.

- Avocado prices have rocketed in recent years by up to 129%, with the average national price in the US of a single Hass avocado reaching $2.10 in 2019, almost doubling in just one year.

- Due to this uncertainty in the prices, the company is not able to sell their produce at the optimal price.

- Your task is to predict the optimal price of the avocardo using the previous sales data of avocardo according to different regions.

In [ ]:
avocado_df = pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/avocado.csv",index_col=0)
avocado_df.head()

         Date  AveragePrice  Total Volume  ...          type  year  region
0  2015-12-27          1.33      64236.62  ...  conventional  2015  Albany
1  2015-12-20          1.35      54876.98  ...  conventional  2015  Albany
2  2015-12-13          0.93     118220.22  ...  conventional  2015  Albany
3  2015-12-06          1.08      78992.15  ...  conventional  2015  Albany
4  2015-11-29          1.28      51039.60  ...  conventional  2015  Albany

[5 rows x 13 columns]

- The dataset contains **weekly retail scan** data for National Retail Volume (units) and price.

- Retail scan data comes directly from retailers’ cash registers based on **actual retail sales** of Hass avocados.

- The column `AveragePrice` is the **average price** of a **single avocado**.

- This is the data that we have to **predict** for future samples.



| Column Name                          | Description                                                                          |
| -------------------------------------|:------------------------------------------------------------------------------------:| 
| Id                               | Unique identity of each observation.                                                    | 
| Date                             | The date of the observation.                                               |
| AveragePrice                             | The average price of a single avocado.                                              | 
| Total Volume                               | Total number of avocados sold.                                                      |
| 4046                           | Total number of avocados with PLU 4046 sold.                                                   |
| 4225                   | Total number of avocados with PLU 4225 sold.                                         |
| 4770                          | Total number of avocados with PLU 4770 sold.                                                        |
| Total Bags                        | Total number of bags sold.                                               |
| Small Bags                        | Total number of small bags sold.                                                         |
| Large Bags                | Total number of large bags sold.                                                |
| XLarge Bags                | Total number of extra-large bags sold.                                                |
| type                | Type of an avocado (conventional or organic).                                                |
| year                | The year of observation.                                                |
| Region                | The city or region of the observation.                                                |

### 2. Halloween Candy Winpercent

- Dataset link : https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/candy-data.csv

#### Problem Statement
- TomTub company sells a large variety of candies worldwide. 

- They want to supply the highest quality of candies which most people will prefer to receive on Halloween. 

- To find the most popular candy, they need to analyze different characteristics of the candy as per the data collected through the survey.

- It is very tough to know the candies preferred by people to receive on Halloween. 

- Currently, they estimate the popularity of candies based on their previous sales but this does not give the ideal results.

- Your task is to predict the winpercent of different candies show that it can be sold during halloween.

In [ ]:
candy_df = pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/candy-data.csv")
candy_df.head()

  competitorname  chocolate  fruity  ...  sugarpercent  pricepercent  winpercent
0      100 Grand          1       0  ...         0.732         0.860   66.971725
1   3 Musketeers          1       0  ...         0.604         0.511   67.602936
2       One dime          0       0  ...         0.011         0.116   32.261086
3    One quarter          0       0  ...         0.011         0.511   46.116505
4      Air Heads          0       1  ...         0.906         0.511   52.341465

[5 rows x 13 columns]

- **Data** was collected by creating a **website** where participants were shown presenting **two** **fun-sized candies** and asked to click on the one they would prefer to receive.

- The dataset comprises of __85 candies and 13 feature columns__. Below is a table showing names of all the columns and their description.

- This is the data that we have to **predict** for future samples.

<br> 


| Column Name     | Description                                               |
| -------------   |:-------------                                            :| 
| competitorname  | Name of competitor candy                                  | 
| chocolate       | Does it contain chocolate?                                |  
| fruity          | Is it fruit flavored?                                     | 
| caramel         | Is there caramel in the candy?                            |   
| peanutalmondy   | Does it contain peanuts, peanut butter or almonds?        |
| nougat          | Does it contain nougat?                                   |
| crispedricewafer| Does it contain crisped rice, wafers, or a cookie component?|
| hard            | Is it a hard candy?                                       |
| bar             | Is it a candy bar?                                        |
| pluribus        | Is it one of many candies in a bag or box?                |
| sugarpercent    | The percentile of sugar it falls under within the data set|
| pricepercent    | The unit price percentile compared to the rest of the set |
| winpercent      | The overall win percentage

### 3. House sale Price Dataset

- Dataset link : https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/house_data.csv

#### Problem Statement
- GetterHome a real estate company has recently acquired a lot of houses in Ames and Iowa. 

- They wanted to set the price of the house according to different aspects of surroundings for that they took a survey asking the different home buyer to describe their dream house, and they probably won't begin with the height of the basement ceiling or the proximity to an east-west railroad. 

- So they collect different aspects of the houses they have and hired a group of data scientist to build an automated solution to predict the price of different houses according to the data they collected.

In [ ]:
house_df = pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/house_data.csv")
house_df.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]


- With 79 explanatory variables describing (almost) every aspect of residential homes in Ames, Iowa,predict the final price of each home.

<br> 


| Column Name     | Description                                               |
| -------------   |:-------------                                            :| 
| SalePrice  | the property's sale price in dollars. This is the target variable that you're trying to predict.                 | 
| MSSubClass       | The building class                             |  
| MSZoning          | The general zoning classification                                  | 
| LotArea         | Linear feet of street connected to property                            |   
| Street   | Type of road access        |
|Alley         | Type of alley access                                   |
| LotShape| General shape of property|
| LandContour            | Lot configuration                                      |
| Utilities      | Type of utilities available                                      |
| LotConfig     | Lot configuration              |
| LandSlope   | Slope of property|
| Neighborhood    | Physical locations within Ames city limits|
| Condition1    | Proximity to main road or railroad     |
| Condition2      | Proximity to main road or railroad (if a second is present)       |
| BldgType      | Type of dwelling       |
| HouseStyle      | Overall material and finish quality      |
| OverallCond      | Overall condition rating       |
| YearBuilt      | Original construction date       |
| YearRemodAdd      | Remodel date      |
| RoofStyle      | Type of roof       |
|RoofMatl      | Roof material      |
| Exterior1st      | Exterior covering on house      |
| Exterior2nd     | Exterior covering on house (if more than one material)      |
| MasVnrType      | Masonry veneer type      |
| MasVnrArea     | Masonry veneer area in square feet      |
| ExterQual      | Exterior material quality       |
| ExterCond      | Present condition of the material on the exterior       |
| Foundation      | Type of foundation       |
| BsmtQual      | Height of the basement       |
| BsmtCond      | General condition of the basement      |
| BsmtExposure     | Walkout or garden level basement walls      |
| BsmtFinType1      | Quality of basement finished area       |
| BsmtFinSF1      | Type 1 finished square feet       |
|BsmtFinType2      | Quality of second finished area (if present)       |
| BsmtFinSF2      | Type 2 finished square feet       |
| BsmtUnfSF     | Unfinished square feet of basement area       |
| TotalBsmtSF      | Total square feet of basement area      |
|Heating      | Type of heating       |
| HeatingQC      | Heating quality and condition       |
| CentralAir     | Central air conditioning      |
| Electrical   | Electrical system    |
|1stFlrSF      | First Floor square feet      |
| 2ndFlrSF     | Second floor square feet       |
| LowQualFinSF     | Low quality finished square feet (all floors)       |
| GrLivArea      | Above grade (ground) living area square feet       |
| BsmtFullBath      | Basement full bathrooms     |
| BsmtHalfBath      | Basement half bathrooms       |
| FullBath      | Full bathrooms above grade      |
| HalfBath      | Half baths above grade       |
| Bedroom     | Number of bedrooms above basement level       |
| Kitchen      | Number of kitchens       |
| KitchenQual      | Kitchen quality       |
| TotRmsAbvGrd     | Total rooms above grade (does not include bathrooms)|
| Functional      | Home functionality rating      |
| Fireplaces      | Number of fireplaces       |
| FireplaceQu      | Fireplace quality       |
| GarageType     | Garage location       |
| GarageYrBlt     | Year garage was built      |
|GarageFinish   | Interior finish of the garage      |
| GarageCars      | Size of garage in car capacity     |
| GarageArea     | Size of garage in square feet     |
| GarageQual      |Garage quality      |
|GarageCond     | Garage condition     |
| PavedDrive      | Paved driveway    |
| WoodDeckSF     | Wood deck area in square feet    |
| OpenPorchSF      | The overall win percentage      |
|OpenPorchSF| OpenPorchSF|
|EnclosedPorch| Enclosed porch area in square feet|
|3SsnPorch| Three season porch area in square feet|
|ScreenPorch| Screen porch area in square feet|
|PoolArea| Pool area in square feet|
|PoolQC| Pool quality|
|Fence| Fence quality|
|MiscFeature| Miscellaneous feature not covered in other categories|
|MiscVal| $Value of miscellaneous feature|
|MoSold| Month Sold|
|YrSold| Year Sold|
|SaleType| Type of sale|
|SaleCondition| Condition of sale|

### 4. FIFA 2018 Dataset

- Dataset link :https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/FIFA%202018%20Statistics.csv

#### Problem Statement
- Football Federation organizes world cup every four years and they collect statistics report about different playing countries and their players. 

- They always spend a lot of time going through the statistics report manually to find the player with the best performance and reward him with the title of man of the match. 

- Recent they have released this stat to the public and one of football fanatic company called DreamFootball has taken up the challenge of predicting the outcome before they announce the title of man of the match. 

- They have hired a group of data scientist to do this task, consider you as one of them.

In [ ]:
fifa_df = pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/FIFA%202018%20Statistics.csv")
fifa_df.head()

         Date          Team  ... Own goals  Own goal Time
0  14-06-2018        Russia  ...       NaN            NaN
1  14-06-2018  Saudi Arabia  ...       NaN            NaN
2  15-06-2018         Egypt  ...       NaN            NaN
3  15-06-2018       Uruguay  ...       NaN            NaN
4  15-06-2018       Morocco  ...       1.0           90.0

[5 rows x 27 columns]

- The Dataset consist of statistics report for differernt countries that too part in FIFA 2018.We need to predict the Man of the match award using this statistics before the official announcement that will be made right after the match.


| Column Name     | Description                                               |
| -------------   |:-------------                                            :| 
|Date |match Date|
|Team| Playing Team|
|Opponent| Opponent Team |
|Goal Scored| Number of goals scored by this team|
|Ball Possession|  %Amount of time ball was in control by the team|
|Attempts| Number of attempts to score goal|
|On| TargetNumber of shots on-target|
|Off| TargetNumber of shots that went off-target|
|Blocked|  Number of opponent team's attempts blocked by the team|
|Corners|  Number of corner shots used|
|Offsides|  Number of off-side events|
|Free Kicks|  Number of free-kicks used|
|SavesNumber |  saves by the goal keeper|
|Pass Accuracy| %Percentage of passes that reached the same team player as aimed|
|Passes|  Total number of passes by the team|
|Distance Covered (Kms)| Total distance covered by the team members in this game|
|Fouls Committed | Number of fouls committed by the team members|
|Yellow Card | Number of Yellow warning received|
|Yellow & Red | Number of Yellow & Red warning received|
|Red | Number of Red cards received|
|Man of the Match|  Did this team member win Man of the Match?|
|1st Goal | When did the team score the 1st goal?|
|Round | Stage of the match|
|PSO |  Was there a penalty shootout (PSO) in this match?|
|Goals in PSO|  Number of goals scored in the Penalty shootout|
|Own goals|  Number of own goals|
|Own goal Time|  When did the team score own goal?|

### 5. Insurance Dataset

- Dataset link :https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/insurance_data.csv

#### Problem Statement
- Haplift one of the largest issuers of life insurance in the USA is hiring passionate data scientists to join a newly-formed Data Science group solving complex challenges and identifying opportunities. 

- The results have been impressive so far but we want more. 

- In a one-click shopping world with on-demand everything, the life insurance application process is antiquated.
- Customers provide extensive information to identify risk classification and eligibility, including scheduling medical exams, a process that takes an average of 30 days.

- The result? People are turned off. That’s why only 40% of U.S. households own individual life insurance. Haplift wants to make it quicker and less labour-intensive for new and existing customers to get a quote while maintaining privacy boundaries.

- By developing a predictive model that accurately classifies risk using a more automated approach, you can greatly impact public perception of the industry.

In [ ]:
fifa_df = pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-2/master/Projects/insurance_data.csv")
fifa_df.head()

   Id  Product_Info_1  ... Medical_Keyword_48  Response
0   2               1  ...                  0         8
1   5               1  ...                  0         4
2   6               1  ...                  0         8
3   7               1  ...                  0         8
4   8               1  ...                  0         8

[5 rows x 128 columns]


- In this dataset, you are provided over a hundred variables describing attributes of life insurance applicants. The task is to predict the "Response" variable for each Id in the test set. "Response" is an ordinal measure of risk that has 8 levels.

<br> 

| Column Name     | Description                                               |
| -------------   |:-------------                                            :| 
|Id|			A unique identifier associated with an application.|
|Product_Info_1-7|	A set of normalized variables relating to the products.|
|Ins_Age|			Normalized age of applicant|
|Ht	|		Normalized height of applicant|
|Wt	|		Normalized weight of applicant|
|BMI|			Normalized BMI of applicant|
|Employment_Info_1-6|	A set of normalized variables relating to the employment history of the applicant.|
|InsuredInfo_1-6|		A set of normalized variables providing information about the applicant.|
|Insurance_History_1-9|	A set of normalized variables relating to the insurance history of the applicant.|
|Family_Hist_1-5|		A set of normalized variables relating to the family history of the applicant.|
|Medical_History_1-41|	A set of normalized variables relating to the medical history of the applicant.|
|Medical_Keyword_1-48| A set of dummy variables relating to the presence of/absence of a medical keyword being associated with the application.|
|Response|		This is the target variable, an ordinal variable relating to the final|